### ISSUE TITLE
AttributeError: 'FieldInfo' object has no attribute 'is_complex' 

### ISSUE THREAD

**Issue by prassr** [bauerji/flask-pydantic#78] opened 2023-10-30 16:09 UTC
Hii All,

Recently, In my project to build a recommendation system with `flask_restful`, I extensively used `flask_pydantic` but faced the error that is shown in title.

This error is raised when I tried to use  `query` like shown [here](https://github.com/prassr/test_api/blob/main/main.py ) (line 61, it is the same code as in documentation)

I extensively created a github repo to diagnose this issue and it can be examined [here](https://github.com/prassr/test_api/tree/main)

The issue exists with vanilla as well as RESTful  flask api.

Flask-Pydantic==0.11.0
Flask-RESTful==0.3.10
pydantic==2.4.2

**Comment by adeadman** [comment] 2023-11-01 11:43
Duplicate of #74 - the latest version of this library only supports Pydantic 1.x

**Comment by yctomwang** [comment] 2023-11-02 03:12
@prassr https://github.com/bauerji/flask-pydantic/pull/77, I have raised a PR for making the code compatible with pydantic2.4.2, feel free to try this version.

**Comment by jkseppan** [comment] 2023-11-06 07:10
There's also an earlier PR #75. Any comment from the maintainer @bauerji as to how to proceed?

**Closed** 2024-01-09 09:05 UTC
